### ISSUE TITLE
no obvious linkage to or from jhrf/telomerecat

### ISSUE THREAD

**Issue by mcast** [cancerit/telomerecat#10]
All the search results point to https://github.com/jhrf/telomerecat or the older Sourceforge project, but there is no fork relationship or pointer-here-from-old to help people find this new one.

Options I can think of
* link from https://github.com/jhrf/telomerecat/issues/9
* re-instate the fork relationship of this project (might require Github Support or a re-pushing)
* asking jhrf for "newer version over there" pointers on the old pages

I found it here because @drjsanger told me (thanks)

**Comment by byb121** [comment]
It seems to me that the repo started to show the link to this repo from two months ago.
