### ISSUE TITLE
lots of lines showing "Could not retrieve index file for...."

### ISSUE THREAD

**Issue by dylanzhao1993** [cancerit/telomerecat#14]
I have also met the same issue as @eb32142 . There are lots of lines showing "Could not retrieve index file for....". So the telomere length cannot be estimated. But I can make sure that the bam file and its index file are under the same path.

**Comment by byb121** [comment]
Would you be able to provide me with a minimum file to reproduce the issue?

**Comment by dylanzhao1993** [comment]
Thank you very much for your quick reply. As I am working on Genomics England environment, there may have some issues of the system now. Now I cannot run telomerecat. But I have tried to copy the index file to the temp dir. It still showed the same errors. And I found that the issue is the same as the issue described by @eb32142.

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87546648-c7107400-c6a1-11ea-8649-13ad6f4e18a2.png)

**Comment by dylanzhao1993** [comment]
There are the errors showed in error file.

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87568703-faf99280-c6bd-11ea-9fda-b5daf21d0cb3.png)

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87579815-73684f80-c6ce-11ea-86ed-b8ec19321761.png)

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87579855-83802f00-c6ce-11ea-8c5b-f09c0848305a.png)

**Comment by dylanzhao1993** [comment]
Hi @byb121 , I have run the program according to your advice for @eb32142 . But it still showed the same error.

**Comment by dylanzhao1993** [comment]
And I have also generated a new index file for this job. So I may have the exact same issue as @eb32142 . Did he resolve this issue eventually?

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87581213-795f3000-c6d0-11ea-9c6c-b0dc54e6ea2c.png)

**Comment by byb121** [comment]
That issue is not solved either. 

Does you BAM file have '@PG' lines in its header? Could you post them here, or probably the whole header if it's ok.

**Comment by dylanzhao1993** [comment]
The BAM file has @PG lines. 
![image](https://user-images.githubusercontent.com/30584390/87596835-afa8a980-c6e8-11ea-9bf9-61849360a8bf.png)

**Comment by byb121** [comment]
It's possible that isaac's bgzip level causes the issue. Could you convert your BAM to an uncompressed BAM and run telomerecat again:

```
samtools view -bu your.bam > new.bam
```

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87643335-a51afe00-c742-11ea-8309-c2b8a49c399a.png)

**Comment by dylanzhao1993** [comment]
Not work. Same error again.

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87643507-e0b5c800-c742-11ea-8795-edfc49330ea2.png)

**Comment by keiranmraine** [comment]
You didn't create a new index for the bam based on that message.

**Comment by dylanzhao1993** [comment]
> You didn't create a new index for the bam based on that message.

Thank you for your notification. I will try it again.

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87653283-3abb8b00-c74d-11ea-9717-ff751558e67b.png)

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87653312-44dd8980-c74d-11ea-91bf-96ca4379e118.png)

**Comment by dylanzhao1993** [comment]
It still cannot work.

**Comment by byb121** [comment]
I suspect it's an issue from pysam's new updates. What's your pysam version?

**Comment by dylanzhao1993** [comment]
![image](https://user-images.githubusercontent.com/30584390/87657790-35f9d580-c753-11ea-8ac9-561b432bd091.png)

**Comment by dylanzhao1993** [comment]
the version is 0.16.0.1

**Comment by byb121** [comment]
Thanks, I'll run some tests to confirm it.

**Comment by byb121** [comment]
Reverting pysam to version 0.15.3 should eliminate those warnings, and perhaps will also eliminate the `truncated file` error as well. Please have a go and let me know your outcome. Thanks.

**Comment by dylanzhao1993** [comment]
@byb121 @keiranmraine It works now. Thank you very much for your help!!!!!!!
