### ISSUE TITLE
Parabam coming to abrupt halt

### ISSUE THREAD

**Issue by dylanzhao1993** [cancerit/telomerecat#15]
![image](https://user-images.githubusercontent.com/30584390/91511267-e857b780-e911-11ea-83a9-ed4483084257.png)

I want to generate the telomere length for about 80k participants and have already generated the telomere length for about 60k participants. In this process, I have met the same error many times. Although the system still shows that this job is running, it has actually stopped. So after a while, I have to check the status for each job, which makes the whole process annoying. So, I will appreciate it if you can help me figure out this issue as not all jobs show this error but a part of them.

**Comment by keiranmraine** [comment]
This should be solved in 4.0.0
