### ISSUE TITLE
Tumour Tissue Sample Estimation and Purity

### ISSUE THREAD

**Issue by DarioS** [cancerit/telomerecat#18]
Can the algorithm incorporate estimates of tumour purity to inform the estimation of copy number and also telomere length? I notice that it was only ever evaluated to work correctly on cell lines, which is a much simpler problem to solve, since there are no intruding normal cells. My tissue samples have tumour purity ranging from 25% to 60% and I'm not confident Telomerecat can produce the correct estimates for those.

**Comment by keiranmraine** [comment]
This tool is currently under maintenance, new features like this are unlikely to be added.  Sorry.
