### ISSUE TITLE
Usage Instructions Missing

### ISSUE THREAD

**Issue by DarioS** [cancerit/telomerecat#19]
There isn't any document describing how to use the software, only how to install it.

**Comment by radwaraed** [comment]
hi DarioS, if you type (telomerecat bam2length --help) or (telomerecat --help), it will guide you on how to use it. Or you can check out this page https://telomerecat.readthedocs.io/en/latest/estimating_telomere.html
I agree with you though. It would be helpful to have a usage example in the readme

**Comment by keiranmraine** [comment]
I've added a minimal guide to getting the command line help for the next release:

https://github.com/cancerit/telomerecat/commit/7cb53f48b81fc386696684403d1202cff22bf379#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
