### ISSUE TITLE
Does Telomerecat accepts CRAM file as input instead of BAM file?

### ISSUE THREAD

**Issue by Ramanandan** [cancerit/telomerecat#21]
Hi,

I would like to use CRAM files instead of BAM files.

Does it accept CRAM files?

**Comment by keiranmraine** [comment]
All the pysam calls are actually in the parabam layer.  They are hardcoded to r/w BAM currently.

It may be possible, but I'm aware of a few places where seek is called on the alignment files which would take some investigation to determine why.

**Comment by keiranmraine** [comment]
See 4.0.0
