### ISSUE TITLE
Telomere length estimation from WXS bam?

### ISSUE THREAD

**Issue by tc86** [cancerit/telomerecat#26]
Thank you for developing this tool. To my understanding, it calculates telomere length from Whole-genome sequencing bam files.
Could this tool calculate telomere length from the Whole exome data?

**Comment by keiranmraine** [comment]
The consensus is that telomerecat would be suboptimal, from an internal discussion:

> telemorecat's normalisation by boundary reads will be impacted by Exome coverage
