### ISSUE TITLE
setup.py asking for parabam release that doesn't exist

### ISSUE THREAD

**Issue by chrispyatt** [cancerit/telomerecat#29]
Installing from tarball (pip install -e) gives the following error:

`
ERROR: Could not find a version that satisfies the requirement parabam>=3.0.0 (from telomerecat==4.0.0) (from versions: none)
ERROR: No matching distribution found for parabam>=3.0.0 (from telomerecat==4.0.0)
`

presumably due to the following line in setup.py:

`
install_requires=["parabam>=3.0.0", "numpy", "pysam", "pandas", "click"],
`

The latest parabam release appears to 2.3.1

**Comment by chrispyatt** [comment]
Just to add: I realise that there is a 3.0.0 pre-release and have added that locally. I had previously acquired dependencies according to requirements.txt which specifies 2.3.1

**Comment by keiranmraine** [comment]
We need to update setup.py to specify the git repo (PEP-508) as we don't have control of the pypi repo (will contact original author to try and sort that out).

Untested:

```
install_requires = [
  'parabam @ https://github.com/cancerit/parabam/releases/download/3.0.0/parabam-3.0.0.tar.gz',
]
```

**Comment by keiranmraine** [comment]
@jhrf, Yaobo has left the group, could you drop me an email at Sanger to arrange the ability to publish updates to pypi?  Thanks

**Comment by byb121** [comment]
Sorry, the lagging mouse clicked on the wrong button...

**Comment by keiranmraine** [comment]
This has been fixed and the relevant versions exist on pypi, documentation update will arrive soon, but a simple install now works as you would expect:

```
pip3 install telomerecat
```
